import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from '../components/Header'


import Link from 'next/link'
import { useRouter } from 'next/router'

export default function Home() {
  const router = useRouter()

  return (
    <>
    <Head>
    <title>OCCEND | Log In</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
    </Head>
  
      <div className={styles.container}>
          

            <Header/>
          <center>

          <form className={styles.loginForm}>
                
                <font face="Work Sans">
                
                <center><h1>Iniciar Sesión</h1></center>

                <input className={styles.inputLogin} type={'email'} placeholder="Correo"></input><br/>
                <input className={styles.inputLogin} type="password" placeholder="Contraseña"></input><br/>
                <center>
                  <button className={styles.btnLog} onClick={()=>router.push('./cliente/')}>Acceder</button>
                  
                  
                </center>
                </font>
            </form>
          


          </center>
          
        </div>
    
    
    </>

    
  )
}
